--- !ruby/object:OAuth::AccessToken
token: de9t4yk8zcbsrvhgkgnaprpwv64eenschbpd2ecsau8yqmj6bavs8ebc7a6tbvzy
secret: RTuH9FF49tTJ
consumer: !ruby/object:OAuth::Consumer
  key: vc76wjg3xyyqawc7m7dttjmq
  secret: NxMYesjNWW
  options:
    :signature_method: HMAC-SHA1
    :request_token_path: /oauth/request_token
    :authorize_path: /oauth/authorize
    :access_token_path: /oauth/access_token
    :proxy: 
    :scheme: :header
    :http_method: :post
    :oauth_version: '1.0'
    :site: http://api.rdio.com
    :authorize_url: https://www.rdio.com/oauth/authorize
  http: !ruby/object:Net::HTTP
    address: api.rdio.com
    port: 80
    local_host: 
    local_port: 
    curr_http_version: '1.1'
    keep_alive_timeout: 2
    last_communicated: 
    close_on_empty_response: false
    socket: 
    started: false
    open_timeout: 30
    read_timeout: 30
    continue_timeout: 
    debug_output: 
    proxy_from_env: true
    proxy_uri: 
    proxy_address: 
    proxy_port: 
    proxy_user: 
    proxy_pass: 
    use_ssl: false
    ssl_context: 
    ssl_session: 
    enable_post_connection_check: true
    sspi_enabled: false
    ca_file: 
    ca_path: 
    cert: 
    cert_store: 
    ciphers: 
    key: 
    ssl_timeout: 
    ssl_version: 
    verify_callback: 
    verify_depth: 
    verify_mode: 0
  http_method: :post
  uri: !ruby/object:URI::HTTP
    scheme: http
    user: 
    password: 
    host: api.rdio.com
    port: 80
    path: ''
    query: 
    opaque: 
    registry: 
    fragment: 
    parser: 
params:
  :oauth_token: de9t4yk8zcbsrvhgkgnaprpwv64eenschbpd2ecsau8yqmj6bavs8ebc7a6tbvzy
  oauth_token: de9t4yk8zcbsrvhgkgnaprpwv64eenschbpd2ecsau8yqmj6bavs8ebc7a6tbvzy
  :oauth_token_secret: RTuH9FF49tTJ
  oauth_token_secret: RTuH9FF49tTJ
response: !ruby/object:Net::HTTPOK
  http_version: '1.1'
  code: '200'
  message: OK
  header:
    x-mashery-responder:
    - prod-p-worker-lax-04.mashery.com
    server:
    - nginx/1.2.4
    date:
    - Thu, 03 Oct 2013 07:09:09 GMT
    content-type:
    - application/json
    connection:
    - close
    x-srv:
    - srv-107-12
    content-language:
    - en
    vary:
    - Accept-Language, Cookie
    cache-control:
    - no-cache
    access-control-allow-origin:
    - '*'
    p3p:
    - CP="This is not a P3P policy. See http://www.rdio.com/legal/privacy-policy for
      more info."
    x-version:
    - '720'
    accept-ranges:
    - bytes
    content-length:
    - '1050'
  body: '{"status": "ok", "result": {"followingUrl": "/people/MatthewSullivan84/people/following/",
    "baseIcon": "user/4/b/d/0000000000a29db4/1/square-100.jpg", "isTrial": false,
    "artistCount": 45, "heavyRotationKey": "e10657204", "networkHeavyRotationKey":
    "h10657204", "icon250": "http://rdio-a.cdn3.rdio.com/user/4/b/d/0000000000a29db4/1/square-250.jpg",
    "albumCount": 53, "libraryVersion": 73, "trackCount": 659, "type": "s", "username":
    "MatthewSullivan84", "isProtected": null, "collectionUrl": "/people/MatthewSullivan84/collection/",
    "playlistsUrl": "/people/MatthewSullivan84/playlists/", "key": "s10657204", "collectionKey":
    "c10657204", "followersUrl": "/people/MatthewSullivan84/people/followers/", "icon":
    "http://rdio-a.cdn3.rdio.com/user/4/b/d/0000000000a29db4/1/square-100.jpg", "icon500":
    "http://rdio-a.cdn3.rdio.com/user/4/b/d/0000000000a29db4/1/square-500.jpg", "displayName":
    "Matthew Sullivan", "firstName": "Matthew", "isUnlimited": true, "url": "/people/MatthewSullivan84/",
    "gender": "m", "lastName": "Sullivan", "isSubscriber": true}}'
  read: true
  uri: 
  decode_content: true
  socket: 
  body_exist: true
