development:
  adapter: postgresql
  encoding: unicode
  database: development_compromise 
  pool: 5
  username: hayduke19us

test:
  adapter: postgresql
  encoding: unicode
  database: test_compromise 
  username: hayduke19us
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  username: hayduke19us
  database: compromise 
  pool: 5
