# Faye
development:
  server: "http://localhost:9292/faye"
  adapter_javascript_url: "http://localhost:9292/faye/faye.js" 
  auth_token: jsdkfsk5ldksf6dafafdafaf
  adapter: "Faye"
  async: true

# Pusher
# development:
#   adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js" 
#   app_id: "YOUR_PUSHER_APP_ID"
#   api_key: "YOUR_PUSHER_API_KEY"
#   auth_token: "YOUR_PUSHER_SECRET"
#   adapter: "Pusher"
#   async: true

test:
  server: "http://localhost:9292/faye"
  adapter_javascript_url: "http://localhost:9292/faye/faye.js" 
  adapter: "Faye"
  auth_token: "secret"
  async: false

production:
  server: "http://warm-wave-8683.herokuapp.com/faye" 
  adap"ter_javascript_url: " http://warm-wave-8683.herokuapp.com/faye/faye.js" 
  adapter: "Faye"
  auth_token: "1fa3c8ffa887b8e8480184be327887670b652839bc4c8b74d55beede8ec83706"
  async: true
